### ISSUE TITLE
Colisión con strings largos

### ISSUE THREAD

**Issue by tracel3ss** [maximilianoangel/Lab_Criptografia#1]
Realizando pruebas a tu código encontré esto:
Para el String:
testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.

```El Hash es: ñėĦĶěĜęĔħıĬęĔēěĜİĲĲěĴęĔēěĜĦĭħıĬę```

Y para el String:
testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.

```El Hash es: ñėĦĶěĜęĔħıĬęĔēěĜİĲĲěĴęĔēěĜĦĭħıĬę```

Si te das cuenta, son el mismo hash, para diferentes strings. Quizás dado que el tiempo apremia, determinar dentro del informe, un número de caractéres donde hay baja probabilidad de colisiones para justificar el uso de tu código. Saludos!

**Comment by maximilianoangel** [comment]
Solucionado. Se agrego una relación con el tamaño original de la palabra al hashear las palabras.
testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.

``ǒșȺɊɎƽƿƼƷƶƾƽȑƼƷƶƾƽƿƼƷƶƾƽȺɍƷƶƾƽƿƼ``

testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.

``ƚśǱƑƆŐŝƄŊǟǦƅǭƄňǞǣǎǍƄſžŐƅǔǆňǞǢƅƇŐ``

Pese a como se ven, ambos son de 32 digitos.

**Comment by tracel3ss** [comment]
Buenisima, acabo de probar y ahora si funciona de maravilla.
Saludos y muy buen trabajo!
